scrapper/urls.py
from django.contrib import admin
from django.urls import path

from .views import index, get, create, update, scrape

urlpatterns = [
    path('', index, name="home"),
    path('list', get, name="scrapper-list"),
    path('create', create, name="scrapper-create"),
    path('update/<int:pk>/', update, name="scrapper-update"),
    path('scrape/<int:pk>/', scrape, name="scrape"),
]

webscrapper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(("scrapper.urls", "scrapper"), namespace="scrapper"))
]

scrapper/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

class ScrapperConfig(models.Model):

    name = models.CharField(max_length=100)
    url = models.URLField()
    css_selector = models.CharField(max_length=255)
    frequency = models.IntegerField(default=60)

    class Meta:
        verbose_name = _("ScrapperConfig")
        verbose_name_plural = _("ScrapperConfigs")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("ScrapperConfig_detail", kwargs={"pk": self.pk})

scrapper/forms.py
from django import forms
from .models import ScrapperConfig

class ScrapperConfigForm(forms.ModelForm):
    
    name = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control"}), required=True, label="Name")
    url = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control"}), required=True, label="Url")
    css_selector = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control"}), required=True, label="Css_selector")
    frequency = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control"}), required=True, label="Frequency")
    
    class Meta:
        model = ScrapperConfig
        fields = ("name", "url", "css_selector", "frequency")

scrapper/views.py
from django.shortcuts import render, redirect
from .models import ScrapperConfig
from .forms import ScrapperConfigForm
from .utils import scrape_all_links
import requests
from bs4 import BeautifulSoup


def index(request):
    return render(
        request=request,
        template_name="index.html"
    )

def get(request):
    configs = ScrapperConfig.objects.all()
    return render(
        request=request,
        template_name="scrapper_view.html",
        context={'configs': configs}
    )

def create(request):
    form = ScrapperConfigForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('scrapper:scrapper-list')
    else:
        form = ScrapperConfigForm()
    return render(request=request,
        template_name="scrapper_form.html",
        context={'form': form}
    )

def update(request, pk):
    configInstance = ScrapperConfig.objects.get(pk=pk)
    form = ScrapperConfigForm(request.POST, instance=configInstance)
    if form.is_valid():
        form.save()
        return redirect('scrapper:scrapper-list')
    else:
        form = ScrapperConfigForm(
            data={
                'name': configInstance.name,
                'url': configInstance.url,
                'css_selector': configInstance.css_selector,
                'frequency': configInstance.frequency
            }
        )
    return render(
        request=request,
        template_name="scrapper_form.html",
        context={'form': form}
    )

def scrape(request, pk):
    configInstance = ScrapperConfig.objects.get(pk=pk)
    response = requests.get(configInstance.url)
    soup = BeautifulSoup(response.content, 'html.parser')
    elements = soup.find_all(configInstance.css_selector)

    return render(
        request=request,
        template_name="scrapper_view.html",
        context={'elements': {element['src'] for element in elements}, 'name': configInstance.name, 'configs': ScrapperConfig.objects.all()}
    )

scrapper/templates/index.html
<!doctype html>
<html lang="en">
    <head>
        <title>Scrapper Home</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
    </head>

    <body>
        <header>
            <nav
                class="navbar navbar-expand-sm navbar-dark bg-dark"
            >
                <div class="container">
                    <a class="navbar-brand" href="{% url 'scrapper:home' %}">ScrapeNow</a>
                    <button
                        class="navbar-toggler d-lg-none"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#collapsibleNavId"
                        aria-controls="collapsibleNavId"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="collapsibleNavId">
                        <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'scrapper:home' %}" aria-current="page"
                                    >Home
                                    <span class="visually-hidden">(current)</span></a
                                >
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'scrapper:scrapper-list' %}">Scrappers</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <main class="container">
            <h1 class="display-1">Welcome to My Scrapper</h1>
        </main>
        <footer>
            <!-- place footer here -->
        </footer>
        <!-- Bootstrap JavaScript Libraries -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

scrapper/templates/scrapper_form.html
!<!doctype html>
<html lang="en">
    <head>
        <title>New Scrapper Configuration</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
    </head>

    <body>
        <header>
            <nav
                class="navbar navbar-expand-sm navbar-dark bg-dark"
            >
                <div class="container">
                    <a class="navbar-brand" href="{% url 'scrapper:home' %}">ScrapeNow</a>
                    <button
                        class="navbar-toggler d-lg-none"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#collapsibleNavId"
                        aria-controls="collapsibleNavId"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="collapsibleNavId">
                        <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'scrapper:home' %}" aria-current="page"
                                    >Home
                                    <span class="visually-hidden">(current)</span></a
                                >
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'scrapper:scrapper-list' %}">Scrappers</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <main class="container">
            <h1>Scrapper Configuration Form</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Submit</button>
            </form>
        </main>
        <footer>
            <!-- place footer here -->
        </footer>
        <!-- Bootstrap JavaScript Libraries -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

scrapper/templates/scrapper_view.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <title>Scrapper Configuration List</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
    </head>

    <body>
        <header>
            <nav
                class="navbar navbar-expand-sm navbar-dark bg-dark"
            >
                <div class="container">
                    <a class="navbar-brand" href="{% url 'scrapper:home' %}">ScrapeNow</a>
                    <button
                        class="navbar-toggler d-lg-none"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#collapsibleNavId"
                        aria-controls="collapsibleNavId"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="collapsibleNavId">
                        <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'scrapper:home' %}" aria-current="page"
                                    >Home
                                    <span class="visually-hidden">(current)</span></a
                                >
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'scrapper:scrapper-list' %}">Scrappers</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <main class="container">
            <div class="row justify-content-center align-items-center g-2">
                <div class="col">
                    <h1 class="display-1">Scrapper Configuration</h1>
                </div>
            </div>
            <div class="row justify-content-center align-items-center g-2">
                <div class="col">
                    <form id="create" method="POST" action="{% url 'scrapper:scrapper-create' %}">
                        {% csrf_token %}
                    </form>
                    <a href="#" onClick="createSubmit()">Create New Site To Scrape</a>
                    <script>
                        function createSubmit() {
                            document.getElementById("create").submit();
                        }
                    </script>
                </div>
            </div>
            <div class="row justify-content-center align-items-center g-2">
                <div class="col">
                    <ul>
                        {% for config in configs %}
                        <li>{{ config.name }} - <a href="#" onClick="scrape{{ forloop.counter }}()">Scrape</a> - <a href="#" onClick="editForm{{ forloop.counter }}()">Edit</a>
                            <form id="list_{{ forloop.counter }}" method="POST" action="{% url 'scrapper:scrapper-update' config.pk %}">
                                {% csrf_token %}
                            </form>
                            <form id="scrape_{{ forloop.counter }}" method="POST" action="{% url 'scrapper:scrape' config.pk %}">
                                {% csrf_token %}
                            </form>
                            <script>
                                function editForm{{ forloop.counter }}() {
                                    document.getElementById("list_{{ forloop.counter }}").submit();
                                }
                                function scrape{{ forloop.counter }}() {
                                    document.getElementById("scrape_{{ forloop.counter }}").submit();
                                }
                            </script>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col">
                    <div class="row justify-content-center align-items-center g-2">
                        <div class="col"><h1>Scrapped Content {% if name %} <span class="display-6">of {{ name }} </span>{% endif %}</h1></div>
                    </div>
                    <div class="row justify-content-center align-items-center g-2">
                        <div class="col">
                            {% for element in elements %}
                            <ul>
                                <li> {{ element }} </li>
                            </ul>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <footer>
            <!-- place footer here -->
        </footer>
        <!-- Bootstrap JavaScript Libraries -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>